# Generated by Django 3.0.11 on 2021-05-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('city_ascii', models.CharField(max_length=120)),
                ('province_id', models.CharField(max_length=2)),
                ('province_name', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('population', models.FloatField()),
                ('density', models.FloatField()),
                ('timezone', models.CharField(max_length=120)),
                ('ranking', models.IntegerField()),
                ('postal', models.TextField()),
                ('city_id', models.CharField(max_length=10)),
            ],
        ),
    ]
