# Generated by Django 3.0.11 on 2021-05-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggestions',
            new_name='Cities',
        ),
    ]
