# Generated by Django 3.0.11 on 2021-05-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_auto_20210519_1305'),
    ]

    operations = [
    ]
